ARG PHP_TAG=7.4-cli

FROM docker.io/library/php:${PHP_TAG} AS base

RUN apt-get -y update && \
    apt-get -y install wget git unzip && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY --from=docker.io/library/composer:latest /usr/bin/composer /usr/bin/composer
