name: Pull Request
on:
    pull_request: ~
jobs:
    php-cs-fixer:
        name: PHP CS Fixer
        timeout-minutes: 10
        runs-on: namespace-profile-default
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.3'
                  extensions: ctype, iconv, opentelemetry
                  ini-values: "memory_limit=-1"
                  coverage: none
                  tools: cs2pr

            - name: Checkout
              uses: actions/checkout@v4

            - name: Get composer cache directory
              id: composer-cache
              run: |
                  echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

            - name: Restore cache
              uses: actions/cache@v4
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-composer-

            - name: Install dependencies
              run: |
                  composer install --no-progress --prefer-dist --optimize-autoloader
            - name: PHP CS Fixer
              run: |
                  bin/php-cs-fixer fix --dry-run --format=checkstyle
    php-unit:
        name: PHPUnit
        timeout-minutes: 10
        runs-on: namespace-profile-default
        services:
            # https://docs.docker.com/samples/library/mysql/
            mysql:
                image: mysql:8.0
                env:
                    MYSQL_ROOT_PASSWORD: root
                ports:
                    - 3306:3306
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        env:
            DATABASE_URL: 'mysql://root:root@127.0.0.1:3306/test?serverVersion=8.0'
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.3'
                  extensions: ctype, iconv, opentelemetry
                  ini-values: "memory_limit=-1"
                  coverage: none

            - name: Checkout
              uses: actions/checkout@v4

            - name: Get composer cache directory
              id: composer-cache
              run: |
                  echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

            - name: Restore cache
              uses: actions/cache@v4
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-composer-

            - name: Install dependencies
              run: |
                  composer install --no-progress --prefer-dist --optimize-autoloader

            - name: Run PHP Unit
              run: |
                bin/phpunit
